In [1]:
from luna.data_processing.utils import *
from luna.models import xgb_clf

In [2]:
df_train = load_data('./example_data/classification/train.csv', 'csv')
df_train

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed,rainfall
0,0,1,1017.4,21.2,20.6,19.9,19.4,87.0,88.0,1.1,60.0,17.2,1
1,1,2,1019.5,16.2,16.9,15.8,15.4,95.0,91.0,0.0,50.0,21.9,1
2,2,3,1024.1,19.4,16.1,14.6,9.3,75.0,47.0,8.3,70.0,18.1,1
3,3,4,1013.4,18.1,17.8,16.9,16.8,95.0,95.0,0.0,60.0,35.6,1
4,4,5,1021.8,21.3,18.4,15.2,9.6,52.0,45.0,3.6,40.0,24.8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2185,2185,361,1014.6,23.2,20.6,19.1,19.9,97.0,88.0,0.1,40.0,22.1,1
2186,2186,362,1012.4,17.2,17.3,16.3,15.3,91.0,88.0,0.0,50.0,35.3,1
2187,2187,363,1013.3,19.0,16.3,14.3,12.6,79.0,79.0,5.0,40.0,32.9,1
2188,2188,364,1022.3,16.4,15.2,13.8,14.7,92.0,93.0,0.1,40.0,18.0,1
2189,2189,365,1013.8,21.2,19.1,18.0,18.0,89.0,88.0,1.0,70.0,48.0,1

In [3]:
target = 'rainfall'

In [4]:
df_train = preprocess_data(df_train, target)

In [5]:
df_train

,id,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed,rainfall
0,-1.731260,-1.701361,0.671702,-0.913809,-0.642199,-0.448815,-0.199457,0.636434,0.681269,-0.729397,-0.560901,-0.465291,1
1,-1.729678,-1.691853,1.043116,-1.798289,-1.350846,-1.259418,-0.956001,1.662224,0.847728,-1.032804,-0.685925,0.009629,1
2,-1.728097,-1.682346,1.856688,-1.232222,-1.504067,-1.496667,-2.109731,-0.902250,-1.593680,1.256536,-0.435876,-0.374349,1
3,-1.726515,-1.672838,-0.035752,-1.462187,-1.178472,-1.041939,-0.691210,1.662224,1.069675,-1.032804,-0.560901,1.393971,1
4,-1.724933,-1.663331,1.449902,-0.896120,-1.063556,-1.378043,-2.052990,-3.851394,-1.704654,-0.039837,-0.810950,0.302665,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2185,1.724933,1.721357,0.176484,-0.560017,-0.642199,-0.606982,-0.104888,1.918671,0.681269,-1.005222,-0.810950,0.029839,1
2186,1.726515,1.730865,-0.212616,-1.621393,-1.274235,-1.160564,-0.974914,1.149329,0.681269,-1.032804,-0.685925,1.363657,1
2187,1.728097,1.740372,-0.053439,-1.302980,-1.465761,-1.555980,-1.485582,-0.389355,0.181890,0.346317,-0.810950,1.121145,1
2188,1.729678,1.749880,1.538334,-1.762910,-1.676440,-1.654834,-1.088396,1.277553,0.958701,-1.005222,-0.810950,-0.384453,1
2189,1.731260,1.759387,0.034993,-0.913809,-0.929488,-0.824460,-0.464247,0.892882,0.681269,-0.756980,-0.435876,2.646952,1

In [6]:
X_train, X_val, y_train, y_val = split_data(df_train, target)

In [7]:
xgb_clf = xgb_clf()
xgb_clf.fit(X_train, y_train)

In [8]:
xgb_clf.evaluate(X_val, y_val)

标签取值范围: [0 1], 标签数量: 2
各类别样本数量:
rainfall
1    319
0    119
Name: count, dtype: int64

{'accuracy': 0.8378995433789954,
 'precision': 0.8318885335224541,
 'recall': 0.8378995433789954,
 'f1': 0.8308189482991385}

In [9]:
# 配置日志系统
import logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

# 然后再调用评估函数
xgb_clf.evaluate(X_val, y_val)

标签取值范围: [0 1], 标签数量: 2
各类别样本数量:
rainfall
1    319
0    119
Name: count, dtype: int64

{'accuracy': 0.8378995433789954,
 'precision': 0.8318885335224541,
 'recall': 0.8378995433789954,
 'f1': 0.8308189482991385}